services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - uploads:/usr/share/nginx/html/uploads
    # ...existing code...

volumes:
  uploads:
