name: Build and deploy Python app to Azure Web App - Tabanna-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          cd pet-adoption-backend
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd pet-adoption-backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Remove the Django collectstatic command
      # - name: collect static files
      #   run: |
      #     cd pet-adoption-backend
      #     python manage.py collectstatic --noinput

      - name: Zip artifact for deployment
        run: |
          cd pet-adoption-backend
          zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            pet-adoption-backend/release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Tabanna-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE }}